<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\bg.jpg" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
    <PackageReference Include="Prism.Unity" Version="8.1.97" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AcrManager.Events\ActManager.Events.csproj" />
    <ProjectReference Include="..\ActManager.Core\ActManager.Core.csproj" />
    <ProjectReference Include="..\ActManager.Forms\ActManager.Forms.csproj" />
    <ProjectReference Include="..\ActManager.Modules.Buildings\ActManager.Modules.Buildings.csproj" />
    <ProjectReference Include="..\ActManager.Modules.CalendarMenu\ActManager.Modules.CalendarMenu.csproj" />
    <ProjectReference Include="..\ActManager.Modules.General\ActManager.Modules.General.csproj" />
    <ProjectReference Include="..\ActManager.Modules.Header\ActManager.Modules.Header.csproj" />
    <ProjectReference Include="..\ActManager.Modules.InfoBoard\ActManager.Modules.InfoBoard.csproj" />
    <ProjectReference Include="..\ActManager.Modules.LeftBoard\ActManager.Modules.LeftBoard.csproj" />
    <ProjectReference Include="..\ActManager.Modules.MainMenu\ActManager.Modules.MainMenu.csproj" />
    <ProjectReference Include="..\ActManager.Modules.RightBoard\ActManager.Modules.RightBoard.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\bg.jpg" />
  </ItemGroup>
</Project>